jobs:
  - job: ${{ parameters.job }}
    displayName: Get input archive
    steps:
      - bash: |
          if [[ -z "${{ parameters.archive_url }}" ]]; then tar -cvzf input.tar.gz --files-from /dev/null; else curl --silent --show-error "${{ parameters.archive_url }}" --output input.tar.gz; fi
        displayName: Get input archive
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'input'
          targetPath: '$(System.DefaultWorkingDirectory)/input.tar.gz'
